"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚º](fg:color_bg3)\
$os\
$username\
[î‚¼](fg:color_bg3 bg:color_bg3)\
$directory\
[î‚¼](fg:color_bg3 bg:color_purple)\
$git_branch$git_status\
[î‚¼](fg:color_purple bg:color_blue)\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python$ruby\
[î‚¼](fg:color_blue bg:color_bg3)\
$docker_context$conda\
[î‚¼](fg:color_bg3 bg:color_bg1)\
$time\
[î‚¼  ](fg:color_bg1)\
$line_break$character"""

palette = 'dracula'

[palettes.dracula]
color_fg0   = '#F8F8F2'
color_bg1   = '#282A36'
color_bg3   = '#44475A'

# Daha aÄŸÄ±r, klasik Dracula mavi
color_blue   = '#6272A4'
color_green  = '#50FA7B'
color_orange = '#FFB86C'
color_purple = '#BD93F9'
color_pink   = '#FF79C6'
color_red    = '#FF5555'
color_yellow = '#F1FA8C'

[os]
disabled = false
style = "bg:color_bg3 fg:color_pink"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"
CachyOS = "ó°£‡"

[username]
show_always = true
style_user = "bg:color_bg3 fg:color_fg0"
style_root = "bg:color_bg3 fg:color_red"
format = '[ $user ]($style)'

[directory]
style = "fg:color_purple bg:color_bg3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™  "
"Downloads" = "ï€™  "
"Music" = "ó°š  "
"Pictures" = "ï€¾  "
"Developer" = "ó°²‹  "
"kod" = "ó°²‹  "
"Code" = "ó°²‹  "

[git_branch]
symbol = "ï˜"
style = "fg:color_bg3 bg:color_purple"      # font daha koyu
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:color_bg3 bg:color_purple"      # aynÄ± ton, bÃ¼tÃ¼nlÃ¼k
format = "[($all_status$ahead_behind )]($style)"

[nodejs]
symbol = "îœ˜"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[c]
symbol = "î˜"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[rust]
symbol = "î¨"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[golang]
symbol = "î˜§"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[php]
symbol = "î˜ˆ"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[java]
symbol = "î‰–"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[kotlin]
symbol = "î˜´"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[haskell]
symbol = "î˜Ÿ"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[python]
symbol = "ğŸ"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[ruby]
symbol = "ğŸ’"
style = "fg:color_bg1 bg:color_blue"
format = "[ $symbol( $version) ]($style)"

[docker_context]
symbol = "ğŸ¬"
style = "fg:color_pink bg:color_bg3"
format = "[ $symbol( $context) ]($style)"

[conda]
style = "fg:color_pink bg:color_bg3"
format = "[ îœ¼  $environment ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg0 bg:color_bg1"
format = "[ ïº  $time ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[â¯](bold fg:color_green)'
error_symbol   = '[â¯](bold fg:color_red)'
vimcmd_symbol             = '[â®](bold fg:color_green)'
vimcmd_replace_one_symbol = '[â®](bold fg:color_pink)'
vimcmd_replace_symbol     = '[â®](bold fg:color_pink)'
vimcmd_visual_symbol      = '[â®](bold fg:color_yellow)'
